/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { CareerControllerGetVacanciesQueryResponse, CareerControllerGetVacanciesQueryParams } from "../types/CareerControllerGetVacancies";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { careerControllerGetVacancies } from "../clients/careerControllerGetVacancies";

export const careerControllerGetVacanciesQueryKey = (params?: CareerControllerGetVacanciesQueryParams) => [{ url: '/api/career/vacancies' }, ...(params ? [params] : [])] as const

export type CareerControllerGetVacanciesQueryKey = ReturnType<typeof careerControllerGetVacanciesQueryKey>

export function careerControllerGetVacanciesQueryOptions(params?: CareerControllerGetVacanciesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = careerControllerGetVacanciesQueryKey(params)
        return queryOptions<CareerControllerGetVacanciesQueryResponse, ResponseErrorConfig<Error>, CareerControllerGetVacanciesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return careerControllerGetVacancies(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/career/vacancies}
 */
export function useCareerControllerGetVacancies<TData = CareerControllerGetVacanciesQueryResponse, TQueryData = CareerControllerGetVacanciesQueryResponse, TQueryKey extends QueryKey = CareerControllerGetVacanciesQueryKey>(params?: CareerControllerGetVacanciesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<CareerControllerGetVacanciesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? careerControllerGetVacanciesQueryKey(params)
         

         const query = useQuery({
          ...careerControllerGetVacanciesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}