/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { CareerControllerGetEpisodesQueryResponse, CareerControllerGetEpisodesQueryParams } from "../types/CareerControllerGetEpisodes";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { careerControllerGetEpisodes } from "../clients/careerControllerGetEpisodes";

export const careerControllerGetEpisodesQueryKey = (params?: CareerControllerGetEpisodesQueryParams) => [{ url: '/api/career/episodes' }, ...(params ? [params] : [])] as const

export type CareerControllerGetEpisodesQueryKey = ReturnType<typeof careerControllerGetEpisodesQueryKey>

export function careerControllerGetEpisodesQueryOptions(params?: CareerControllerGetEpisodesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = careerControllerGetEpisodesQueryKey(params)
        return queryOptions<CareerControllerGetEpisodesQueryResponse, ResponseErrorConfig<Error>, CareerControllerGetEpisodesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return careerControllerGetEpisodes(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/career/episodes}
 */
export function useCareerControllerGetEpisodes<TData = CareerControllerGetEpisodesQueryResponse, TQueryData = CareerControllerGetEpisodesQueryResponse, TQueryKey extends QueryKey = CareerControllerGetEpisodesQueryKey>(params?: CareerControllerGetEpisodesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<CareerControllerGetEpisodesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? careerControllerGetEpisodesQueryKey(params)
         

         const query = useQuery({
          ...careerControllerGetEpisodesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}