/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { CareerControllerGetProofsQueryResponse } from "../types/CareerControllerGetProofs";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { careerControllerGetProofs } from "../clients/careerControllerGetProofs";

export const careerControllerGetProofsQueryKey = () => [{ url: '/api/career/proofs' }] as const

export type CareerControllerGetProofsQueryKey = ReturnType<typeof careerControllerGetProofsQueryKey>

export function careerControllerGetProofsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = careerControllerGetProofsQueryKey()
        return queryOptions<CareerControllerGetProofsQueryResponse, ResponseErrorConfig<Error>, CareerControllerGetProofsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return careerControllerGetProofs({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/career/proofs}
 */
export function useCareerControllerGetProofs<TData = CareerControllerGetProofsQueryResponse, TQueryData = CareerControllerGetProofsQueryResponse, TQueryKey extends QueryKey = CareerControllerGetProofsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<CareerControllerGetProofsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? careerControllerGetProofsQueryKey()
         

         const query = useQuery({
          ...careerControllerGetProofsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}