/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { CareerControllerGetProfileQueryResponse } from "../types/CareerControllerGetProfile";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { careerControllerGetProfile } from "../clients/careerControllerGetProfile";

export const careerControllerGetProfileQueryKey = () => [{ url: '/api/career/profile' }] as const

export type CareerControllerGetProfileQueryKey = ReturnType<typeof careerControllerGetProfileQueryKey>

export function careerControllerGetProfileQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = careerControllerGetProfileQueryKey()
        return queryOptions<CareerControllerGetProfileQueryResponse, ResponseErrorConfig<Error>, CareerControllerGetProfileQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return careerControllerGetProfile({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/career/profile}
 */
export function useCareerControllerGetProfile<TData = CareerControllerGetProfileQueryResponse, TQueryData = CareerControllerGetProfileQueryResponse, TQueryKey extends QueryKey = CareerControllerGetProfileQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<CareerControllerGetProfileQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? careerControllerGetProfileQueryKey()
         

         const query = useQuery({
          ...careerControllerGetProfileQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}