/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CareerControllerGetRecommendationsMutationRequest, CareerControllerGetRecommendationsMutationResponse } from "../types/CareerControllerGetRecommendations";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { careerControllerGetRecommendations } from "../clients/careerControllerGetRecommendations";

export const careerControllerGetRecommendationsMutationKey = () => [{ url: '/api/career/recommendations' }] as const

export type CareerControllerGetRecommendationsMutationKey = ReturnType<typeof careerControllerGetRecommendationsMutationKey>

export function careerControllerGetRecommendationsMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CareerControllerGetRecommendationsMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = careerControllerGetRecommendationsMutationKey()
        return mutationOptions<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerGetRecommendationsMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return careerControllerGetRecommendations(data, config)
          },
        })

}

/**
 * {@link /api/career/recommendations}
 */
export function useCareerControllerGetRecommendations<TContext>(options: 
{
  mutation?: UseMutationOptions<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerGetRecommendationsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CareerControllerGetRecommendationsMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? careerControllerGetRecommendationsMutationKey()

          const baseOptions = careerControllerGetRecommendationsMutationOptions(config) as UseMutationOptions<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerGetRecommendationsMutationRequest}, TContext>
          

          return useMutation<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerGetRecommendationsMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerGetRecommendationsMutationRequest}, TContext>
      
}