/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CareerControllerSaveProfileMutationRequest, CareerControllerSaveProfileMutationResponse } from "../types/CareerControllerSaveProfile";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { careerControllerSaveProfile } from "../clients/careerControllerSaveProfile";

export const careerControllerSaveProfileMutationKey = () => [{ url: '/api/career/profile' }] as const

export type CareerControllerSaveProfileMutationKey = ReturnType<typeof careerControllerSaveProfileMutationKey>

export function careerControllerSaveProfileMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CareerControllerSaveProfileMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = careerControllerSaveProfileMutationKey()
        return mutationOptions<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerSaveProfileMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return careerControllerSaveProfile(data, config)
          },
        })

}

/**
 * {@link /api/career/profile}
 */
export function useCareerControllerSaveProfile<TContext>(options: 
{
  mutation?: UseMutationOptions<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerSaveProfileMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CareerControllerSaveProfileMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? careerControllerSaveProfileMutationKey()

          const baseOptions = careerControllerSaveProfileMutationOptions(config) as UseMutationOptions<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerSaveProfileMutationRequest}, TContext>
          

          return useMutation<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerSaveProfileMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerSaveProfileMutationRequest}, TContext>
      
}