/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CareerControllerCompleteEpisodeMutationRequest, CareerControllerCompleteEpisodeMutationResponse } from "../types/CareerControllerCompleteEpisode";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { careerControllerCompleteEpisode } from "../clients/careerControllerCompleteEpisode";

export const careerControllerCompleteEpisodeMutationKey = () => [{ url: '/api/career/episodes/complete' }] as const

export type CareerControllerCompleteEpisodeMutationKey = ReturnType<typeof careerControllerCompleteEpisodeMutationKey>

export function careerControllerCompleteEpisodeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CareerControllerCompleteEpisodeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = careerControllerCompleteEpisodeMutationKey()
        return mutationOptions<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerCompleteEpisodeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return careerControllerCompleteEpisode(data, config)
          },
        })

}

/**
 * {@link /api/career/episodes/complete}
 */
export function useCareerControllerCompleteEpisode<TContext>(options: 
{
  mutation?: UseMutationOptions<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerCompleteEpisodeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CareerControllerCompleteEpisodeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? careerControllerCompleteEpisodeMutationKey()

          const baseOptions = careerControllerCompleteEpisodeMutationOptions(config) as UseMutationOptions<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerCompleteEpisodeMutationRequest}, TContext>
          

          return useMutation<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerCompleteEpisodeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, {data: CareerControllerCompleteEpisodeMutationRequest}, TContext>
      
}