/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { CareerControllerSyncVacanciesMutationResponse } from "../types/CareerControllerSyncVacancies";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { careerControllerSyncVacancies } from "../clients/careerControllerSyncVacancies";

export const careerControllerSyncVacanciesMutationKey = () => [{ url: '/api/career/vacancies/sync' }] as const

export type CareerControllerSyncVacanciesMutationKey = ReturnType<typeof careerControllerSyncVacanciesMutationKey>

export function careerControllerSyncVacanciesMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = careerControllerSyncVacanciesMutationKey()
        return mutationOptions<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return careerControllerSyncVacancies(config)
          },
        })

}

/**
 * {@link /api/career/vacancies/sync}
 */
export function useCareerControllerSyncVacancies<TContext>(options: 
{
  mutation?: UseMutationOptions<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? careerControllerSyncVacanciesMutationKey()

          const baseOptions = careerControllerSyncVacanciesMutationOptions(config) as UseMutationOptions<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, void, TContext>
          

          return useMutation<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, void, TContext>
      
}