/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UserControllerAuthenticateMutationRequest, UserControllerAuthenticateMutationResponse, UserControllerAuthenticate400 } from "../types/UserControllerAuthenticate";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { userControllerAuthenticate } from "../clients/userControllerAuthenticate";

export const userControllerAuthenticateMutationKey = () => [{ url: '/api/user/tg-auth' }] as const

export type UserControllerAuthenticateMutationKey = ReturnType<typeof userControllerAuthenticateMutationKey>

export function userControllerAuthenticateMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UserControllerAuthenticateMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = userControllerAuthenticateMutationKey()
        return mutationOptions<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, {data: UserControllerAuthenticateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return userControllerAuthenticate(data, config)
          },
        })

}

/**
 * @summary Создать запись
 * {@link /api/user/tg-auth}
 */
export function useUserControllerAuthenticate<TContext>(options: 
{
  mutation?: UseMutationOptions<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, {data: UserControllerAuthenticateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UserControllerAuthenticateMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? userControllerAuthenticateMutationKey()

          const baseOptions = userControllerAuthenticateMutationOptions(config) as UseMutationOptions<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, {data: UserControllerAuthenticateMutationRequest}, TContext>
          

          return useMutation<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, {data: UserControllerAuthenticateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, {data: UserControllerAuthenticateMutationRequest}, TContext>
      
}