/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { UserControllerGetQueryResponse, UserControllerGet400 } from "../types/UserControllerGet";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { userControllerGet } from "../clients/userControllerGet";

export const userControllerGetQueryKey = () => [{ url: '/api/user' }] as const

export type UserControllerGetQueryKey = ReturnType<typeof userControllerGetQueryKey>

export function userControllerGetQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = userControllerGetQueryKey()
        return queryOptions<UserControllerGetQueryResponse, ResponseErrorConfig<UserControllerGet400>, UserControllerGetQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return userControllerGet({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Получить запись пользователя
 * {@link /api/user}
 */
export function useUserControllerGet<TData = UserControllerGetQueryResponse, TQueryData = UserControllerGetQueryResponse, TQueryKey extends QueryKey = UserControllerGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<UserControllerGetQueryResponse, ResponseErrorConfig<UserControllerGet400>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? userControllerGetQueryKey()
         

         const query = useQuery({
          ...userControllerGetQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<UserControllerGet400>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}