/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerProfileDto } from "./CareerProfileDto";

export type CareerProfileStateDto = {
    /**
     * @type string
    */
    profileKey: string;
    /**
     * @type object
    */
    profile: CareerProfileDto;
    /**
     * @type string
    */
    updatedAt: string;
};