/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerProfileDto = {
    /**
     * @type string
    */
    mode: string | null;
    /**
     * @type string
    */
    age: string;
    /**
     * @type string
    */
    education: string | null;
    /**
     * @type string
    */
    goal: string | null;
    /**
     * @type string
    */
    preference: string | null;
    /**
     * @type string
    */
    teamStyle: string | null;
    /**
     * @type string
    */
    rhythm: string | null;
    /**
     * @type string
    */
    hardSkills: string;
    /**
     * @type string
    */
    softSkills: string;
    /**
     * @type string
    */
    experience: string;
    /**
     * @type string
    */
    targetVacancy: string | null;
};