/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerProfileStateDto } from "./CareerProfileStateDto";

export type CareerControllerGetProfile200 = CareerProfileStateDto;

export type CareerControllerGetProfileQueryResponse = CareerControllerGetProfile200;

export type CareerControllerGetProfileQuery = {
    Response: CareerControllerGetProfile200;
    Errors: any;
};