/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerProofDto } from "./CareerProofDto";

export type CareerControllerGetProofs200 = CareerProofDto[];

export type CareerControllerGetProofsQueryResponse = CareerControllerGetProofs200;

export type CareerControllerGetProofsQuery = {
    Response: CareerControllerGetProofs200;
    Errors: any;
};