/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerEpisodeDto = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    duration: string;
    /**
     * @type string
    */
    status: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    nextAction: string;
    /**
     * @type string
    */
    details: string;
    /**
     * @type string
    */
    impact: string;
    /**
     * @type number
    */
    order: number;
    /**
     * @type string
    */
    trackId: string;
    /**
     * @type boolean
    */
    isCurrent: boolean;
    /**
     * @type boolean
    */
    completed: boolean;
};