/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerSkillScoreDto } from "./CareerSkillScoreDto";
import type { CareerTrackDto } from "./CareerTrackDto";

export type CareerRecommendationsResponseDto = {
    /**
     * @type array
    */
    tracks: CareerTrackDto[];
    /**
     * @type string
    */
    nearestRole: string;
    /**
     * @type number
    */
    profileReadyPercent: number;
    /**
     * @type array
    */
    hardSkills: CareerSkillScoreDto[];
    /**
     * @type array
    */
    softSkills: CareerSkillScoreDto[];
    /**
     * @type boolean
    */
    llmUsed: boolean;
    /**
     * @type string
    */
    llmError: string | null;
};