/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CompleteCareerEpisodeDto } from "./CompleteCareerEpisodeDto";
import type { CompleteCareerEpisodeResponseDto } from "./CompleteCareerEpisodeResponseDto";

export type CareerControllerCompleteEpisode200 = CompleteCareerEpisodeResponseDto;

export type CareerControllerCompleteEpisodeMutationRequest = CompleteCareerEpisodeDto;

export type CareerControllerCompleteEpisodeMutationResponse = CareerControllerCompleteEpisode200;

export type CareerControllerCompleteEpisodeMutation = {
    Response: CareerControllerCompleteEpisode200;
    Request: CareerControllerCompleteEpisodeMutationRequest;
    Errors: any;
};