/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerProfileDto } from "./CareerProfileDto";
import type { CareerRecommendationsResponseDto } from "./CareerRecommendationsResponseDto";

export type CareerControllerGetRecommendations200 = CareerRecommendationsResponseDto;

export type CareerControllerGetRecommendationsMutationRequest = CareerProfileDto;

export type CareerControllerGetRecommendationsMutationResponse = CareerControllerGetRecommendations200;

export type CareerControllerGetRecommendationsMutation = {
    Response: CareerControllerGetRecommendations200;
    Request: CareerControllerGetRecommendationsMutationRequest;
    Errors: any;
};