/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerTrackDto = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type number
    */
    score: number;
    /**
     * @type string
    */
    eta: string;
    /**
     * @type string
    */
    reason: string;
};