/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerVacancyDto = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    mode: string;
    /**
     * @type number
    */
    match: number;
    /**
     * @type string
    */
    matchReason: string;
    /**
     * @type string
    */
    gap: string;
    /**
     * @type string
    */
    plan: string;
    /**
     * @type string
    */
    sourceUrl: string;
    /**
     * @type string
    */
    applyUrl: string;
    /**
     * @type string
    */
    sourceName: string;
};