/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerControllerSyncVacancies200 = {
    /**
     * @type string | undefined
    */
    syncedAt?: string;
};

export type CareerControllerSyncVacanciesMutationResponse = CareerControllerSyncVacancies200;

export type CareerControllerSyncVacanciesMutation = {
    Response: CareerControllerSyncVacancies200;
    Errors: any;
};