/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerProfileDto } from "./CareerProfileDto";
import type { CareerProfileStateDto } from "./CareerProfileStateDto";

export type CareerControllerSaveProfile200 = CareerProfileStateDto;

export type CareerControllerSaveProfileMutationRequest = CareerProfileDto;

export type CareerControllerSaveProfileMutationResponse = CareerControllerSaveProfile200;

export type CareerControllerSaveProfileMutation = {
    Response: CareerControllerSaveProfile200;
    Request: CareerControllerSaveProfileMutationRequest;
    Errors: any;
};