/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerProofDto = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    status: string;
};