/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CareerSkillScoreDto = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type number
    */
    score: number;
    /**
     * @type string
    */
    reason: string;
};