/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerEpisodeDto } from "./CareerEpisodeDto";

export type CareerControllerGetEpisodesQueryParams = {
    /**
     * @type string | undefined
    */
    trackId?: string;
};

export type CareerControllerGetEpisodes200 = CareerEpisodeDto[];

export type CareerControllerGetEpisodesQueryResponse = CareerControllerGetEpisodes200;

export type CareerControllerGetEpisodesQuery = {
    Response: CareerControllerGetEpisodes200;
    QueryParams: CareerControllerGetEpisodesQueryParams;
    Errors: any;
};