/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CareerVacancyDto } from "./CareerVacancyDto";

export type CareerControllerGetVacanciesQueryParams = {
    /**
     * @type string | undefined
    */
    trackId?: string;
};

export type CareerControllerGetVacancies200 = CareerVacancyDto[];

export type CareerControllerGetVacanciesQueryResponse = CareerControllerGetVacancies200;

export type CareerControllerGetVacanciesQuery = {
    Response: CareerControllerGetVacancies200;
    QueryParams: CareerControllerGetVacanciesQueryParams;
    Errors: any;
};