/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CompleteCareerEpisodeResponseDto = {
    /**
     * @type string
    */
    episodeId: string;
    /**
     * @type boolean
    */
    completed: boolean;
    /**
     * @type string
    */
    message: string;
};