/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CompleteCareerEpisodeDto = {
    /**
     * @type string
    */
    episodeId: string;
    /**
     * @type string
    */
    trackId?: string | null;
};