/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const errorDtoMessageEnum = {
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    AUTH_FAIL: "AUTH_FAIL",
    ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND",
    ENTITY_CREATION_FAIL: "ENTITY_CREATION_FAIL"
} as const;

export type ErrorDtoMessageEnumKey = (typeof errorDtoMessageEnum)[keyof typeof errorDtoMessageEnum];

export type ErrorDto = {
    /**
     * @type string | undefined
    */
    message?: ErrorDtoMessageEnumKey;
    /**
     * @type string
    */
    error: string;
    /**
     * @type number
    */
    statusCode: number;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type array | undefined
    */
    messages?: string[];
};