/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TgAuthResponseDto = {
    /**
     * @type string
    */
    accessToken: string;
    /**
     * @type boolean
    */
    isNewUser: boolean;
};