/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorDto } from "./ErrorDto";
import type { User } from "./User";

export type UserControllerGet200 = User;

export type UserControllerGet400 = ErrorDto;

export type UserControllerGetQueryResponse = UserControllerGet200;

export type UserControllerGetQuery = {
    Response: UserControllerGet200;
    Errors: UserControllerGet400;
};