/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorDto } from "./ErrorDto";
import type { TgAuthDto } from "./TgAuthDto";
import type { TgAuthResponseDto } from "./TgAuthResponseDto";

export type UserControllerAuthenticate200 = TgAuthResponseDto;

export type UserControllerAuthenticate400 = ErrorDto;

export type UserControllerAuthenticateMutationRequest = TgAuthDto;

export type UserControllerAuthenticateMutationResponse = UserControllerAuthenticate200;

export type UserControllerAuthenticateMutation = {
    Response: UserControllerAuthenticate200;
    Request: UserControllerAuthenticateMutationRequest;
    Errors: UserControllerAuthenticate400;
};