/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type User = {
    /**
     * @type string
    */
    id: string;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
    /**
     * @type string, date-time
    */
    deletedAt: string;
    /**
     * @type number
    */
    telegramId: number;
    /**
     * @type string
    */
    telegramUsername: string;
    /**
     * @type string
    */
    telegramFirstName: string;
    /**
     * @type string
    */
    telegramLastName: string;
    /**
     * @type boolean
    */
    telegramIsPremium: boolean;
    /**
     * @type string
    */
    telegramLanguageCode: string;
};