/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerCompleteEpisodeMutationRequest, CareerControllerCompleteEpisodeMutationResponse } from "../types/CareerControllerCompleteEpisode";

function getCareerControllerCompleteEpisodeUrl() {
  const res = { method: 'POST', url: `/api/career/episodes/complete` as const }
  return res
}

/**
 * {@link /api/career/episodes/complete}
 */
export async function careerControllerCompleteEpisode(data: CareerControllerCompleteEpisodeMutationRequest, config: Partial<RequestConfig<CareerControllerCompleteEpisodeMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CareerControllerCompleteEpisodeMutationResponse, ResponseErrorConfig<Error>, CareerControllerCompleteEpisodeMutationRequest>({ method : "POST", url : getCareerControllerCompleteEpisodeUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}