/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerGetProofsQueryResponse } from "../types/CareerControllerGetProofs";

function getCareerControllerGetProofsUrl() {
  const res = { method: 'GET', url: `/api/career/proofs` as const }
  return res
}

/**
 * {@link /api/career/proofs}
 */
export async function careerControllerGetProofs(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CareerControllerGetProofsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCareerControllerGetProofsUrl().url.toString(), ... requestConfig })
  return res.data
}