/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerGetProfileQueryResponse } from "../types/CareerControllerGetProfile";

function getCareerControllerGetProfileUrl() {
  const res = { method: 'GET', url: `/api/career/profile` as const }
  return res
}

/**
 * {@link /api/career/profile}
 */
export async function careerControllerGetProfile(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CareerControllerGetProfileQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCareerControllerGetProfileUrl().url.toString(), ... requestConfig })
  return res.data
}