/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerSyncVacanciesMutationResponse } from "../types/CareerControllerSyncVacancies";

function getCareerControllerSyncVacanciesUrl() {
  const res = { method: 'POST', url: `/api/career/vacancies/sync` as const }
  return res
}

/**
 * {@link /api/career/vacancies/sync}
 */
export async function careerControllerSyncVacancies(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CareerControllerSyncVacanciesMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getCareerControllerSyncVacanciesUrl().url.toString(), ... requestConfig })
  return res.data
}