/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerSaveProfileMutationRequest, CareerControllerSaveProfileMutationResponse } from "../types/CareerControllerSaveProfile";

function getCareerControllerSaveProfileUrl() {
  const res = { method: 'POST', url: `/api/career/profile` as const }
  return res
}

/**
 * {@link /api/career/profile}
 */
export async function careerControllerSaveProfile(data: CareerControllerSaveProfileMutationRequest, config: Partial<RequestConfig<CareerControllerSaveProfileMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CareerControllerSaveProfileMutationResponse, ResponseErrorConfig<Error>, CareerControllerSaveProfileMutationRequest>({ method : "POST", url : getCareerControllerSaveProfileUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}