/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerGetVacanciesQueryResponse, CareerControllerGetVacanciesQueryParams } from "../types/CareerControllerGetVacancies";

function getCareerControllerGetVacanciesUrl() {
  const res = { method: 'GET', url: `/api/career/vacancies` as const }
  return res
}

/**
 * {@link /api/career/vacancies}
 */
export async function careerControllerGetVacancies(params?: CareerControllerGetVacanciesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CareerControllerGetVacanciesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCareerControllerGetVacanciesUrl().url.toString(), params, ... requestConfig })
  return res.data
}