/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerGetEpisodesQueryResponse, CareerControllerGetEpisodesQueryParams } from "../types/CareerControllerGetEpisodes";

function getCareerControllerGetEpisodesUrl() {
  const res = { method: 'GET', url: `/api/career/episodes` as const }
  return res
}

/**
 * {@link /api/career/episodes}
 */
export async function careerControllerGetEpisodes(params?: CareerControllerGetEpisodesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<CareerControllerGetEpisodesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getCareerControllerGetEpisodesUrl().url.toString(), params, ... requestConfig })
  return res.data
}