/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { CareerControllerGetRecommendationsMutationRequest, CareerControllerGetRecommendationsMutationResponse } from "../types/CareerControllerGetRecommendations";

function getCareerControllerGetRecommendationsUrl() {
  const res = { method: 'POST', url: `/api/career/recommendations` as const }
  return res
}

/**
 * {@link /api/career/recommendations}
 */
export async function careerControllerGetRecommendations(data: CareerControllerGetRecommendationsMutationRequest, config: Partial<RequestConfig<CareerControllerGetRecommendationsMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CareerControllerGetRecommendationsMutationResponse, ResponseErrorConfig<Error>, CareerControllerGetRecommendationsMutationRequest>({ method : "POST", url : getCareerControllerGetRecommendationsUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}