/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UserControllerGetQueryResponse, UserControllerGet400 } from "../types/UserControllerGet";

function getUserControllerGetUrl() {
  const res = { method: 'GET', url: `/api/user` as const }
  return res
}

/**
 * @summary Получить запись пользователя
 * {@link /api/user}
 */
export async function userControllerGet(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<UserControllerGetQueryResponse, ResponseErrorConfig<UserControllerGet400>, unknown>({ method : "GET", url : getUserControllerGetUrl().url.toString(), ... requestConfig })
  return res.data
}