/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/client";
import type { UserControllerAuthenticateMutationRequest, UserControllerAuthenticateMutationResponse, UserControllerAuthenticate400 } from "../types/UserControllerAuthenticate";

function getUserControllerAuthenticateUrl() {
  const res = { method: 'POST', url: `/api/user/tg-auth` as const }
  return res
}

/**
 * @summary Создать запись
 * {@link /api/user/tg-auth}
 */
export async function userControllerAuthenticate(data: UserControllerAuthenticateMutationRequest, config: Partial<RequestConfig<UserControllerAuthenticateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UserControllerAuthenticateMutationResponse, ResponseErrorConfig<UserControllerAuthenticate400>, UserControllerAuthenticateMutationRequest>({ method : "POST", url : getUserControllerAuthenticateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}